# Definieren des Basis Docker Images
FROM mongo:4.4.14

# Erstellen des Anwendungsverzeichnisses
WORKDIR /usr/src/app

# Freigeben des Ports, unter dem
# MondoDb läuft
EXPOSE 27017

# Starten des definierten npm-Scripts
# CMD [ "npm", "start" ]
# Alternativ Starten im Debug-Modus
# CMD [ "npm", "start:debug" ]
